version: '3.8'

services:
  odoo-mcp-server:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: odoo_mcp_server
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    environment:
      # Configurazione Odoo
      - ODOO_URL=${ODOO_URL:-http://localhost:8069}
      - ODOO_DB=${ODOO_DB:-odoo}
      - ODOO_USER=${ODOO_USER:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD:-admin}
      - CONNECTION_TYPE=sse
    networks:
      - mcp-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_mcp_client
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Configurazione n8n
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=${WEBHOOK_URL:-http://localhost:5678/}
      # Configurazione Client MCP
      - MCP_SERVERS={"odoo-docker":{"url":"http://odoo-mcp-server:8080","enable":true,"autoApprove":[]}}
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      - odoo-mcp-server
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  n8n_data:
