version: '3.8'

services:
  mcp-odoo-server:
    build: .
    container_name: mcp-odoo-panda
    restart: unless-stopped
    environment:
      # Odoo connection settings (required)
      - ODOO_URL=${ODOO_URL:-http://odoo:8069}
      - ODOO_DB=${ODOO_DB:-odoo}
      - ODOO_USER=${ODOO_USER:-admin}
      - ODOO_PASSWORD=${ODOO_PASSWORD:-admin}
      
      # MCP Server configuration
      - PROTOCOL=${PROTOCOL:-xmlrpc}
      - CONNECTION_TYPE=${CONNECTION_TYPE:-streamable_http}
      - LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}
      
      # Performance settings
      - POOL_SIZE=${POOL_SIZE:-5}
      - TIMEOUT=${TIMEOUT:-30}
      - SESSION_TIMEOUT_MINUTES=${SESSION_TIMEOUT_MINUTES:-60}
      - REQUESTS_PER_MINUTE=${REQUESTS_PER_MINUTE:-60}
      - RATE_LIMIT_MAX_WAIT_SECONDS=${RATE_LIMIT_MAX_WAIT_SECONDS:-30}
      
      # Python settings
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    ports:
      - "${HTTP_PORT:-8080}:8080"
    
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    
    networks:
      - mcp-network
    
    depends_on:
      - odoo
    
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  odoo:
    image: odoo:18.0
    container_name: odoo-mcp
    restart: unless-stopped
    environment:
      - HOST=${ODOO_HOST:-db}
      - USER=${ODOO_DB_USER:-odoo}
      - PASSWORD=${ODOO_DB_PASSWORD:-odoo}
      - POSTGRES_DB=${ODOO_DB:-odoo}
    ports:
      - "${ODOO_PORT:-8069}:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo-addons:/mnt/extra-addons
    networks:
      - mcp-network
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-mcp
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${ODOO_DB:-odoo}
      - POSTGRES_USER=${ODOO_DB_USER:-odoo}
      - POSTGRES_PASSWORD=${ODOO_DB_PASSWORD:-odoo}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - mcp-network

volumes:
  odoo-data:
  postgres-data:

networks:
  mcp-network:
    driver: bridge