# Configurazione Server MCP Odoo

# Configurazione Odoo
odoo_url: http://localhost:8069
database: odoo
username: admin
api_key: admin

# Configurazione Server
protocol: xmlrpc  # o jsonrpc
connection_type: stdio  # o sse
requests_per_minute: 120
rate_limit_max_wait_seconds: 5
pool_size: 5
timeout: 30
session_timeout_minutes: 60

# Configurazione SSE (solo se connection_type: sse)
sse_queue_maxsize: 1000
allowed_origins: ["*"]

# Configurazione Logging
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: StreamHandler
      level: INFO
    - type: FileHandler
      filename: server.log
      level: DEBUG 